name: "test for consuming fe-reusable-workflow"

on:
  workflow_dispatch:
    inputs:
      docker_image_name:
        required: true
        type: string

jobs:
  consume-reusable:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Trigger Reusable Workflow
        uses: ./.github/workflows/fe-reusable-workflow.yml
