name: "test for consuming fe-reusable-workflow"

on:
  workflow_dispatch:
    inputs:
      docker_image_name:
        required: true
        type: string

jobs:
  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/fe-reusable-workflow.yml
    with:
      docker_image_name: ${{ inputs.docker_image_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.TOKEN  }}
